# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BONI Blog
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  We know how important is the content. That's why we created BONI.
  BONI helps you to create exciting content and pin it up to
  object or place and then deliver it when an end user is nearby.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://boni.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude: [gulpfile.js, package.json,node_modules]

# Authors
authors:
  atsvetkov:
    display_name: Angel Tsvetkov
    avatar: atsvetkov.png
    email: angel.tsvetkov@mail.com
